version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: edusphere-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: edusphere
      MONGO_INITDB_ROOT_PASSWORD: edusphere_dev
      MONGO_INITDB_DATABASE: edusphere
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: edusphere-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
